### ISSUE TITLE
Please add background-color parameter

### ISSUE THREAD

**Issue by ivaquero** [FlandiaYingman/note-me#1]
This is a helpful package, and it would be better to be more tweakable.

**Comment by flandia** [comment]
Sure, will do.

**Comment by flandia** [comment]
I assume you would like something like this?

![image](https://github.com/FlandiaYingman/note-me/assets/9929037/01ff3e03-7b41-44cd-9073-ba21dfef7a64)

**Comment by ivaquero** [comment]
Yes, exactly.

**Comment by flandia** [comment]
I just submitted v0.1.1 to the typst packages repository and this will be included.
